AUCHAN_CATEGORIES = ['https://www.auchan.ru//catalog/novinki/', 
'https://www.auchan.ru//catalog/sobstvennye-marki-ashan/', 
'https://www.auchan.ru//catalog/tovary-za-marki/', 
'https://www.auchan.ru//catalog/podarki-na-vse-sluchai/', 
'https://www.auchan.ru//catalog/velikiy-post-akcii/', 
'https://www.auchan.ru//catalog/tovary-dlya-dachi/', 
'https://www.auchan.ru//catalog/sdelano-v-ashan-akcii/', 
'https://www.auchan.ru//catalog/moloko-syr-yayca/', 
'https://www.auchan.ru//catalog/ptica-myaso/', 
'https://www.auchan.ru//catalog/ryba-ikra-moreprodukty/', 
'https://www.auchan.ru//catalog/fermerskie-produkty/', 
'https://www.auchan.ru//catalog/syry/', 
'https://www.auchan.ru//catalog/ovoschi-frukty-zelen-griby-yagody/', 
'https://www.auchan.ru//catalog/alkogol/', 
'https://www.auchan.ru//catalog/zamorozhennye-produkty/', 
'https://www.auchan.ru//catalog/kolbasnye-izdeliya/', 
'https://www.auchan.ru//catalog/kulinariya/', 
'https://www.auchan.ru//catalog/hlebnaya-vypechka/', 
'https://www.auchan.ru//catalog/bakaleya/', 
'https://www.auchan.ru//catalog/konditerskie-izdeliya/', 
'https://www.auchan.ru//catalog/orehi-suhofrukty-sneki/', 
'https://www.auchan.ru//catalog/chay-kofe-sladosti/', 
'https://www.auchan.ru//catalog/voda-soki-napitki/', 
'https://www.auchan.ru//catalog/zdorovyy-vybor/', 
'https://www.auchan.ru//catalog/sportivnoe-pitanie-i-bady/', 
'https://www.auchan.ru//catalog/nastoyaschaya-aziya/',
 'https://www.auchan.ru//catalog/zootovary/', 
 'https://www.auchan.ru//catalog/uborka-i-bytovaya-himiya/', 
 'https://www.auchan.ru//catalog/krasota-i-gigiena/', 
 'https://www.auchan.ru//catalog/vse-dlya-detey/',
  'https://www.auchan.ru//catalog/zabota-o-zdorove/', 
  'https://www.auchan.ru//catalog/kanctovary/', 
  'https://www.auchan.ru//catalog/igrushki/', 
  'https://www.auchan.ru//catalog/cvety/', 
  'https://www.auchan.ru//catalog/tovary-dlya-doma/',
   'https://www.auchan.ru//catalog/kuhnya/', 
   'https://www.auchan.ru//catalog/mebel/', 
   'https://www.auchan.ru//catalog/elektronika/',
    'https://www.auchan.ru//catalog/bytovaya-tehnika/',
     'https://www.auchan.ru//catalog/stroitelstvo-i-remont/',
      'https://www.auchan.ru//catalog/avtotovary/', 
      'https://www.auchan.ru//catalog/otdyh-na-dache/', 
      'https://www.auchan.ru//catalog/odezhda-obuv-i-aksessuary/', 
      'https://www.auchan.ru//catalog/sport-i-otdyh/', 
      'https://www.auchan.ru//catalog/vse-dlya-mam-akcii/',
       'https://www.auchan.ru//catalog/bagazh/', 
       'https://www.auchan.ru//catalog/knigi-zhurnaly/', 
       'https://www.auchan.ru//catalog/dlya-prazdnika/']


AUCHAN_FOOD_CATEGORIES_DICT = {
    'https://www.auchan.ru//catalog/moloko-syr-yayca/': "Молоко, сыр, яйца",
    'https://www.auchan.ru//catalog/ptica-myaso/': "Птица, мясо",
    'https://www.auchan.ru//catalog/ryba-ikra-moreprodukty/': "Рыба, икра, морепродукты",
    'https://www.auchan.ru//catalog/syry/': "Сыры",
    'https://www.auchan.ru//catalog/ovoschi-frukty-zelen-griby-yagody/': "Овощи, фрукты, зелень, грибы, ягоды",
    'https://www.auchan.ru//catalog/zamorozhennye-produkty/': "Замороженные продукты",
    'https://www.auchan.ru//catalog/kolbasnye-izdeliya/': "Колбасные изделия",
    'https://www.auchan.ru//catalog/hlebnaya-vypechka/': "Хлебо-булочные изделия",
    'https://www.auchan.ru//catalog/bakaleya/': "Бакалея",
    'https://www.auchan.ru//catalog/konditerskie-izdeliya/': "Кондитерские изделия",
    'https://www.auchan.ru//catalog/orehi-suhofrukty-sneki/': "Орехи, сухофрукты, снеки",
    'https://www.auchan.ru//catalog/chay-kofe-sladosti/': "Чай, кофе, сладости",
    'https://www.auchan.ru//catalog/voda-soki-napitki/': "Вода, соки, напитки"
    }

LENTA_CATEGORIES_DICT = {
'https://lenta.com/catalog/cvety-rasteniya-17815/': 'Цветы, растения',
'https://lenta.com/catalog/postno-i-polezno-23608/': 'Постно и полезно',
'https://lenta.com/catalog/sejjchas-sezon-23263/': 'Сейчас сезон',
'https://lenta.com/catalog/osobenno-vygodno-1893/': 'Особенно выгодно',
'https://lenta.com/catalog/novinki-19305/': 'Новинки',
'https://lenta.com/catalog/tolko-v-lente-18359/': 'Только в Ленте',
'https://lenta.com/catalog/alkogol-17036/': 'Алкоголь',
'https://lenta.com/catalog/gotovaya-eda-42/': 'Готовая еда',
'https://lenta.com/catalog/ovoshchi-frukty-144/': 'Овощи, фрукты',
'https://lenta.com/catalog/ryba-ikra-moreprodukty-183/': 'Рыба, икра, морепродукты',
'https://lenta.com/catalog/myaso-i-ptica-136/': 'Мясо и птица',
'https://lenta.com/catalog/molochnye-produkty-3/': 'Молочные продукты',
'https://lenta.com/catalog/kolbasa-sosiski-754/': 'Колбаса, сосиски',
'https://lenta.com/catalog/syry-2/': 'Сыры',
'https://lenta.com/catalog/zamorozka-77/': 'Заморозка',
'https://lenta.com/catalog/makarony-krupy-muka-25/': 'Макароны, крупы, мука',
'https://lenta.com/catalog/hleb-i-vypechka-165/': 'Хлеб и выпечка',
'https://lenta.com/catalog/kofe-chajj-kakao-242/': 'Кофе, чай, какао',
'https://lenta.com/catalog/dacha-i-sad-1731/': 'Дача и сад',
'https://lenta.com/catalog/kanctovary-hobbi-knigi-18030/': 'Канцтовары, хобби, книги',
'https://lenta.com/catalog/tovary-dlya-prazdnika-17997/': 'Товары для праздника',
'https://lenta.com/catalog/postno-i-polezno-23608/': 'Постно и полезно',
'https://lenta.com/catalog/sejjchas-sezon-23263/': 'Сейчас сезон',
'https://lenta.com/catalog/osobenno-vygodno-1893/': 'Особенно выгодно',
'https://lenta.com/catalog/novinki-19305/': 'Новинки',
'https://lenta.com/catalog/tolko-v-lente-18359/': 'Только в Ленте',
'https://lenta.com/catalog/alkogol-17036/': 'Алкоголь',
'https://lenta.com/catalog/gotovaya-eda-42/': 'Готовая еда',
'https://lenta.com/catalog/ovoshchi-frukty-144/': 'Овощи, фрукты',
'https://lenta.com/catalog/ryba-ikra-moreprodukty-183/': 'Рыба, икра, морепродукты',
'https://lenta.com/catalog/myaso-i-ptica-136/': 'Мясо и птица',
'https://lenta.com/catalog/molochnye-produkty-3/': 'Молочные продукты',
'https://lenta.com/catalog/kolbasa-sosiski-754/': 'Колбаса, сосиски',
'https://lenta.com/catalog/syry-2/': 'Сыры',
'https://lenta.com/catalog/zamorozka-77/': 'Заморозка',
'https://lenta.com/catalog/makarony-krupy-muka-25/': 'Макароны, крупы, мука',
'https://lenta.com/catalog/hleb-i-vypechka-165/': 'Хлеб и выпечка',
'https://lenta.com/catalog/kofe-chajj-kakao-242/': 'Кофе, чай, какао',
'https://lenta.com/catalog/maslo-sousy-specii-20824/': 'Масло, соусы, специи',
'https://lenta.com/catalog/napitki-4/': 'Напитки',
'https://lenta.com/catalog/sladosti-1028/': 'Сладости',
'https://lenta.com/catalog/konservaciya-94/': 'Консервация',
'https://lenta.com/catalog/sneki-20195/': 'Снеки',
'https://lenta.com/catalog/zdorovoe-pitanie-1879/': 'Здоровое питание',
'https://lenta.com/catalog/avtotovary-18199/': 'Автотовары',
'https://lenta.com/catalog/bytovaya-himiya-1070/': 'Бытовая химия',
'https://lenta.com/catalog/uhod-i-gigiena-3509/': 'Уход и гигиена',
'https://lenta.com/catalog/kuhnya-1427/': 'Кухня',
'https://lenta.com/catalog/dom-interer-17400/': 'Дом, интерьер',
'https://lenta.com/catalog/tovary-dlya-zhivotnyh-18134/': 'Товары для животных',
'https://lenta.com/catalog/tovary-dlya-detejj-19433/': 'Товары для детей',
'https://lenta.com/catalog/detskoe-pitanie-19327/': 'Детское питание',
'https://lenta.com/catalog/sport-i-otdyh-1419/': 'Спорт и отдых',
'https://lenta.com/catalog/odezhda-i-aksessuary-2673/': 'Одежда и аксессуары',
'https://lenta.com/catalog/bytovaya-tehnika-1439/': 'Бытовая техника',
'https://lenta.com/catalog/dacha-i-sad-1731/': 'Дача и сад',
'https://lenta.com/catalog/kanctovary-hobbi-knigi-18030/': 'Канцтовары, хобби, книги',
'https://lenta.com/catalog/tovary-dlya-prazdnika-17997/': 'Товары для праздника'
}

LENTA_FOOD_CATEGORIES_DICT = {
'https://lenta.com/catalog/ovoshchi-frukty-144/': 'Овощи, фрукты',
'https://lenta.com/catalog/ryba-ikra-moreprodukty-183/': 'Рыба, икра, морепродукты',
'https://lenta.com/catalog/myaso-i-ptica-136/': 'Мясо и птица',
'https://lenta.com/catalog/molochnye-produkty-3/': 'Молочные продукты',
'https://lenta.com/catalog/kolbasa-sosiski-754/': 'Колбаса, сосиски',
'https://lenta.com/catalog/syry-2/': 'Сыры',
'https://lenta.com/catalog/zamorozka-77/': 'Заморозка',
'https://lenta.com/catalog/makarony-krupy-muka-25/': 'Макароны, крупы, мука',
'https://lenta.com/catalog/hleb-i-vypechka-165/': 'Хлеб и выпечка',
'https://lenta.com/catalog/kofe-chajj-kakao-242/': 'Кофе, чай, какао',
'https://lenta.com/catalog/maslo-sousy-specii-20824/': 'Масло, соусы, специи',
'https://lenta.com/catalog/napitki-4/': 'Напитки',
'https://lenta.com/catalog/sladosti-1028/': 'Сладости',
'https://lenta.com/catalog/konservaciya-94/': 'Консервация',
'https://lenta.com/catalog/sneki-20195/': 'Снеки',
'https://lenta.com/catalog/detskoe-pitanie-19327/': 'Детское питание'
}

DIXY_GOODS_CATEGORIES_DICT = {
'https://dixy.ru/catalog/skidki-po-karte/': 'Скидки по карте', 
'https://dixy.ru/catalog/ovoshchi-frukty/': 'Овощи, фрукты', 
'https://dixy.ru/catalog/gotovaya-eda/': 'Готовая еда', 
'https://dixy.ru/catalog/molochnye-produkty-yaytsa/': 'Молочные продукты, яйцо', 
'https://dixy.ru/catalog/syry/': 'Сыры', 
'https://dixy.ru/catalog/myaso-ptitsa/': 'Мясо, птица', 
'https://dixy.ru/catalog/myasnaya-gastronomiya/': 'Мясная гастрономия', 
'https://dixy.ru/catalog/khleb-i-vypechka/': 'Хлеб и выпечка', 
'https://dixy.ru/catalog/ryba-moreprodukty-ikra/': 'Рыба, морепродукты, икра', 
'https://dixy.ru/catalog/bakaleya/': 'Бакалея', 
'https://dixy.ru/catalog/konservy/': 'Консервы', 
'https://dixy.ru/catalog/zamorojennye-produkty/': 'Замороженные продукты', 
'https://dixy.ru/catalog/sousy-spetsii/': 'Соусы, специи', 
'https://dixy.ru/catalog/konditerskie-izdeliya-torty/': 'Кондитерские изделия, торты', 
'https://dixy.ru/catalog/chipsy-orekhi-i-sneki/': 'Чипсы, орехи и снеки', 
'https://dixy.ru/catalog/chay-kofe-kakao/': 'Чай, кофе, какао', 
'https://dixy.ru/catalog/voda-soki-napitki/': 'Вода, соки, напитки', 
'https://dixy.ru/catalog/dlya-zdorovogo-pitaniya/': 'Для здорового питания', 
'https://dixy.ru/catalog/detskoe-pitanie/': 'Детское питание', 
'https://dixy.ru/catalog/tovary-dlya-detey/': 'Товары для детей', 
'https://dixy.ru/catalog/tovary-dlya-jivotnykh/': 'Товары для животных',
'https://dixy.ru/catalog/bytovaya-khimiya/': 'Бытовая химия', 
'https://dixy.ru/catalog/gigiena-i-kosmetika/': 'Гигиена и косметика', 
'https://dixy.ru/catalog/tovary-dlya-doma-i-dachi/': 'Товары для дома и дачи', 
'https://dixy.ru/catalog/alkogolnye-napitki/': 'Алкогольные напитки'
}

DIXY_FOOD_CATEGORIES_DICT = {
'https://dixy.ru/catalog/ovoshchi-frukty/': 'Овощи, фрукты', 
'https://dixy.ru/catalog/molochnye-produkty-yaytsa/': 'Молочные продукты, яйцо', 
'https://dixy.ru/catalog/syry/': 'Сыры', 
'https://dixy.ru/catalog/myaso-ptitsa/': 'Мясо, птица', 
'https://dixy.ru/catalog/myasnaya-gastronomiya/': 'Мясная гастрономия', 
'https://dixy.ru/catalog/khleb-i-vypechka/': 'Хлеб и выпечка', 
'https://dixy.ru/catalog/ryba-moreprodukty-ikra/': 'Рыба, морепродукты, икра', 
'https://dixy.ru/catalog/bakaleya/': 'Бакалея', 
'https://dixy.ru/catalog/konservy/': 'Консервы', 
'https://dixy.ru/catalog/zamorojennye-produkty/': 'Замороженные продукты', 
'https://dixy.ru/catalog/sousy-spetsii/': 'Соусы, специи', 
'https://dixy.ru/catalog/konditerskie-izdeliya-torty/': 'Кондитерские изделия, торты', 
'https://dixy.ru/catalog/chipsy-orekhi-i-sneki/': 'Чипсы, орехи и снеки', 
'https://dixy.ru/catalog/chay-kofe-kakao/': 'Чай, кофе, какао', 
'https://dixy.ru/catalog/voda-soki-napitki/': 'Вода, соки, напитки', 
'https://dixy.ru/catalog/detskoe-pitanie/': 'Детское питание', 
}


CHIZHIK_CATEGORIES_DICT = {
"https://chizhik.club/catalog/molochnye-produkty-yaytso--264C39140/": "Молочные продукты, яйцо",
"https://chizhik.club/catalog/syry-i-maslo--264C39153/": "Сыры и масло", 
"https://chizhik.club/catalog/krupy-i-makarony--264C39160/": "Крупы и макароны", 
"https://chizhik.club/catalog/khleb-i-vypechka--264C39166/": "Хлеб и выпечка", 
"https://chizhik.club/catalog/maslo-sousy-spetsii--264C39172/": ">Масло, соусы, специи",
"https://chizhik.club/catalog/konservatsiya--264C39207/": "Консервация",
"https://chizhik.club/catalog/myaso-i-ptitsa--264C39184/":"Мясо и птица",
"https://chizhik.club/catalog/myasnaya-gastronomiya--264C39179/": "Мясная гастрономия",
"https://chizhik.club/catalog/ryba-i-moreprodukty--264C39189/" : "Рыба и морепродукты",
"https://chizhik.club/catalog/zamorozhennye-produkty--264C39201/" : "Замороженные продукты",
"https://chizhik.club/catalog/ovoshchi-i-frukty--264C39196/" : "Овощи и фрукты",
"https://chizhik.club/catalog/orekhi-chipsy-sneki--264C39253/" : "Орехи, чипсы, снеки",
"https://chizhik.club/catalog/sladosti-deserty-morozhenoe--264C39235/": "Сладости, десерты, мороженое",
"https://chizhik.club/catalog/chay-kofe--264C39224/" : "Чай, кофе", 
"https://chizhik.club/catalog/napitki--264C39228/" : "Напитки",
"https://chizhik.club/catalog/detskie-tovary--264C39214/": "Детские товары",
"https://chizhik.club/catalog/tovary-dlya-doma--264C39270/": "Товары для дома",
"https://chizhik.club/catalog/sredstva-gigieny--264C39258/": "Средства гигиены",
"https://chizhik.club/catalog/stirka-i-uborka--264C39277/": "Стирка и уборка",
"https://chizhik.club/catalog/tovary-dlya-zhivotnykh--264C39282/": "Товары для животных",
"https://chizhik.club/catalog/odezhda-obuv-tekstil--264C39286/": "Одежда, обувь, текстиль",
"https://chizhik.club/catalog/energetiki--264C39307/": "Энергетики",
"https://chizhik.club/catalog/alkogol--264C39295/": "Алкоголь",
}

CHIZHIK_FOOD_CATEGORIES_DICT = {
"https://chizhik.club/catalog/molochnye-produkty-yaytso--264C39140/": "Молочные продукты, яйцо",
"https://chizhik.club/catalog/syry-i-maslo--264C39153/": "Сыры и масло", 
"https://chizhik.club/catalog/krupy-i-makarony--264C39160/": "Крупы и макароны", 
"https://chizhik.club/catalog/khleb-i-vypechka--264C39166/": "Хлеб и выпечка", 
"https://chizhik.club/catalog/maslo-sousy-spetsii--264C39172/": ">Масло, соусы, специи",
"https://chizhik.club/catalog/konservatsiya--264C39207/": "Консервация",
"https://chizhik.club/catalog/myaso-i-ptitsa--264C39184/":"Мясо и птица",
"https://chizhik.club/catalog/myasnaya-gastronomiya--264C39179/": "Мясная гастрономия",
"https://chizhik.club/catalog/ryba-i-moreprodukty--264C39189/" : "Рыба и морепродукты",
"https://chizhik.club/catalog/zamorozhennye-produkty--264C39201/" : "Замороженные продукты",
"https://chizhik.club/catalog/ovoshchi-i-frukty--264C39196/" : "Овощи и фрукты",
"https://chizhik.club/catalog/orekhi-chipsy-sneki--264C39253/" : "Орехи, чипсы, снеки",
"https://chizhik.club/catalog/sladosti-deserty-morozhenoe--264C39235/": "Сладости, десерты, мороженое",
"https://chizhik.club/catalog/chay-kofe--264C39224/" : "Чай, кофе", 
"https://chizhik.club/catalog/napitki--264C39228/" : "Напитки",
"https://chizhik.club/catalog/energetiki--264C39307/": "Энергетики",
}