AUCHAN_CATEGORIES = ['https://www.auchan.ru//catalog/novinki/', 
'https://www.auchan.ru//catalog/sobstvennye-marki-ashan/', 
'https://www.auchan.ru//catalog/tovary-za-marki/', 
'https://www.auchan.ru//catalog/podarki-na-vse-sluchai/', 
'https://www.auchan.ru//catalog/velikiy-post-akcii/', 
'https://www.auchan.ru//catalog/tovary-dlya-dachi/', 
'https://www.auchan.ru//catalog/sdelano-v-ashan-akcii/', 
'https://www.auchan.ru//catalog/moloko-syr-yayca/', 
'https://www.auchan.ru//catalog/ptica-myaso/', 
'https://www.auchan.ru//catalog/ryba-ikra-moreprodukty/', 
'https://www.auchan.ru//catalog/fermerskie-produkty/', 
'https://www.auchan.ru//catalog/syry/', 
'https://www.auchan.ru//catalog/ovoschi-frukty-zelen-griby-yagody/', 
'https://www.auchan.ru//catalog/alkogol/', 
'https://www.auchan.ru//catalog/zamorozhennye-produkty/', 
'https://www.auchan.ru//catalog/kolbasnye-izdeliya/', 
'https://www.auchan.ru//catalog/kulinariya/', 
'https://www.auchan.ru//catalog/hlebnaya-vypechka/', 
'https://www.auchan.ru//catalog/bakaleya/', 
'https://www.auchan.ru//catalog/konditerskie-izdeliya/', 
'https://www.auchan.ru//catalog/orehi-suhofrukty-sneki/', 
'https://www.auchan.ru//catalog/chay-kofe-sladosti/', 
'https://www.auchan.ru//catalog/voda-soki-napitki/', 
'https://www.auchan.ru//catalog/zdorovyy-vybor/', 
'https://www.auchan.ru//catalog/sportivnoe-pitanie-i-bady/', 
'https://www.auchan.ru//catalog/nastoyaschaya-aziya/',
 'https://www.auchan.ru//catalog/zootovary/', 
 'https://www.auchan.ru//catalog/uborka-i-bytovaya-himiya/', 
 'https://www.auchan.ru//catalog/krasota-i-gigiena/', 
 'https://www.auchan.ru//catalog/vse-dlya-detey/',
  'https://www.auchan.ru//catalog/zabota-o-zdorove/', 
  'https://www.auchan.ru//catalog/kanctovary/', 
  'https://www.auchan.ru//catalog/igrushki/', 
  'https://www.auchan.ru//catalog/cvety/', 
  'https://www.auchan.ru//catalog/tovary-dlya-doma/',
   'https://www.auchan.ru//catalog/kuhnya/', 
   'https://www.auchan.ru//catalog/mebel/', 
   'https://www.auchan.ru//catalog/elektronika/',
    'https://www.auchan.ru//catalog/bytovaya-tehnika/',
     'https://www.auchan.ru//catalog/stroitelstvo-i-remont/',
      'https://www.auchan.ru//catalog/avtotovary/', 
      'https://www.auchan.ru//catalog/otdyh-na-dache/', 
      'https://www.auchan.ru//catalog/odezhda-obuv-i-aksessuary/', 
      'https://www.auchan.ru//catalog/sport-i-otdyh/', 
      'https://www.auchan.ru//catalog/vse-dlya-mam-akcii/',
       'https://www.auchan.ru//catalog/bagazh/', 
       'https://www.auchan.ru//catalog/knigi-zhurnaly/', 
       'https://www.auchan.ru//catalog/dlya-prazdnika/']


AUCHAN_FOOD_CATEGORIES_DICT = {
    'https://www.auchan.ru//catalog/moloko-syr-yayca/': "Молоко, сыр, яйца",
    'https://www.auchan.ru//catalog/ptica-myaso/': "Птица, мясо",
    'https://www.auchan.ru//catalog/ryba-ikra-moreprodukty/': "Рыба, икра, морепродукты",
    'https://www.auchan.ru//catalog/syry/': "Сыры",
    'https://www.auchan.ru//catalog/ovoschi-frukty-zelen-griby-yagody/': "Овощи, фрукты, зелень, грибы, ягоды",
    'https://www.auchan.ru//catalog/zamorozhennye-produkty/': "Замороженные продукты",
    'https://www.auchan.ru//catalog/kolbasnye-izdeliya/': "Колбасные изделия",
    'https://www.auchan.ru//catalog/hlebnaya-vypechka/': "Хлебо-булочные изделия",
    'https://www.auchan.ru//catalog/bakaleya/': "Бакалея",
    'https://www.auchan.ru//catalog/konditerskie-izdeliya/': "Кондитерские изделия",
    'https://www.auchan.ru//catalog/orehi-suhofrukty-sneki/': "Орехи, сухофрукты, снеки",
    'https://www.auchan.ru//catalog/chay-kofe-sladosti/': "Чай, кофе, сладости",
    'https://www.auchan.ru//catalog/voda-soki-napitki/': "Вода, соки, напитки"
    }

LENTA_CATEGORIES_DICT = {
'https://lenta.com/catalog/cvety-rasteniya-17815/': 'Цветы, растения',
'https://lenta.com/catalog/postno-i-polezno-23608/': 'Постно и полезно',
'https://lenta.com/catalog/sejjchas-sezon-23263/': 'Сейчас сезон',
'https://lenta.com/catalog/osobenno-vygodno-1893/': 'Особенно выгодно',
'https://lenta.com/catalog/novinki-19305/': 'Новинки',
'https://lenta.com/catalog/tolko-v-lente-18359/': 'Только в Ленте',
'https://lenta.com/catalog/alkogol-17036/': 'Алкоголь',
'https://lenta.com/catalog/gotovaya-eda-42/': 'Готовая еда',
'https://lenta.com/catalog/ovoshchi-frukty-144/': 'Овощи, фрукты',
'https://lenta.com/catalog/ryba-ikra-moreprodukty-183/': 'Рыба, икра, морепродукты',
'https://lenta.com/catalog/myaso-i-ptica-136/': 'Мясо и птица',
'https://lenta.com/catalog/molochnye-produkty-3/': 'Молочные продукты',
'https://lenta.com/catalog/kolbasa-sosiski-754/': 'Колбаса, сосиски',
'https://lenta.com/catalog/syry-2/': 'Сыры',
'https://lenta.com/catalog/zamorozka-77/': 'Заморозка',
'https://lenta.com/catalog/makarony-krupy-muka-25/': 'Макароны, крупы, мука',
'https://lenta.com/catalog/hleb-i-vypechka-165/': 'Хлеб и выпечка',
'https://lenta.com/catalog/kofe-chajj-kakao-242/': 'Кофе, чай, какао',
'https://lenta.com/catalog/dacha-i-sad-1731/': 'Дача и сад',
'https://lenta.com/catalog/kanctovary-hobbi-knigi-18030/': 'Канцтовары, хобби, книги',
'https://lenta.com/catalog/tovary-dlya-prazdnika-17997/': 'Товары для праздника',
'https://lenta.com/catalog/postno-i-polezno-23608/': 'Постно и полезно',
'https://lenta.com/catalog/sejjchas-sezon-23263/': 'Сейчас сезон',
'https://lenta.com/catalog/osobenno-vygodno-1893/': 'Особенно выгодно',
'https://lenta.com/catalog/novinki-19305/': 'Новинки',
'https://lenta.com/catalog/tolko-v-lente-18359/': 'Только в Ленте',
'https://lenta.com/catalog/alkogol-17036/': 'Алкоголь',
'https://lenta.com/catalog/gotovaya-eda-42/': 'Готовая еда',
'https://lenta.com/catalog/ovoshchi-frukty-144/': 'Овощи, фрукты',
'https://lenta.com/catalog/ryba-ikra-moreprodukty-183/': 'Рыба, икра, морепродукты',
'https://lenta.com/catalog/myaso-i-ptica-136/': 'Мясо и птица',
'https://lenta.com/catalog/molochnye-produkty-3/': 'Молочные продукты',
'https://lenta.com/catalog/kolbasa-sosiski-754/': 'Колбаса, сосиски',
'https://lenta.com/catalog/syry-2/': 'Сыры',
'https://lenta.com/catalog/zamorozka-77/': 'Заморозка',
'https://lenta.com/catalog/makarony-krupy-muka-25/': 'Макароны, крупы, мука',
'https://lenta.com/catalog/hleb-i-vypechka-165/': 'Хлеб и выпечка',
'https://lenta.com/catalog/kofe-chajj-kakao-242/': 'Кофе, чай, какао',
'https://lenta.com/catalog/maslo-sousy-specii-20824/': 'Масло, соусы, специи',
'https://lenta.com/catalog/napitki-4/': 'Напитки',
'https://lenta.com/catalog/sladosti-1028/': 'Сладости',
'https://lenta.com/catalog/konservaciya-94/': 'Консервация',
'https://lenta.com/catalog/sneki-20195/': 'Снеки',
'https://lenta.com/catalog/zdorovoe-pitanie-1879/': 'Здоровое питание',
'https://lenta.com/catalog/avtotovary-18199/': 'Автотовары',
'https://lenta.com/catalog/bytovaya-himiya-1070/': 'Бытовая химия',
'https://lenta.com/catalog/uhod-i-gigiena-3509/': 'Уход и гигиена',
'https://lenta.com/catalog/kuhnya-1427/': 'Кухня',
'https://lenta.com/catalog/dom-interer-17400/': 'Дом, интерьер',
'https://lenta.com/catalog/tovary-dlya-zhivotnyh-18134/': 'Товары для животных',
'https://lenta.com/catalog/tovary-dlya-detejj-19433/': 'Товары для детей',
'https://lenta.com/catalog/detskoe-pitanie-19327/': 'Детское питание',
'https://lenta.com/catalog/sport-i-otdyh-1419/': 'Спорт и отдых',
'https://lenta.com/catalog/odezhda-i-aksessuary-2673/': 'Одежда и аксессуары',
'https://lenta.com/catalog/bytovaya-tehnika-1439/': 'Бытовая техника',
'https://lenta.com/catalog/dacha-i-sad-1731/': 'Дача и сад',
'https://lenta.com/catalog/kanctovary-hobbi-knigi-18030/': 'Канцтовары, хобби, книги',
'https://lenta.com/catalog/tovary-dlya-prazdnika-17997/': 'Товары для праздника'
}

LENTA_FOOD_CATEGORIES_DICT = {
'https://lenta.com/catalog/ovoshchi-frukty-144/': 'Овощи, фрукты',
'https://lenta.com/catalog/ryba-ikra-moreprodukty-183/': 'Рыба, икра, морепродукты',
'https://lenta.com/catalog/myaso-i-ptica-136/': 'Мясо и птица',
'https://lenta.com/catalog/molochnye-produkty-3/': 'Молочные продукты',
'https://lenta.com/catalog/kolbasa-sosiski-754/': 'Колбаса, сосиски',
'https://lenta.com/catalog/syry-2/': 'Сыры',
'https://lenta.com/catalog/zamorozka-77/': 'Заморозка',
'https://lenta.com/catalog/makarony-krupy-muka-25/': 'Макароны, крупы, мука',
'https://lenta.com/catalog/hleb-i-vypechka-165/': 'Хлеб и выпечка',
'https://lenta.com/catalog/kofe-chajj-kakao-242/': 'Кофе, чай, какао',
'https://lenta.com/catalog/maslo-sousy-specii-20824/': 'Масло, соусы, специи',
'https://lenta.com/catalog/napitki-4/': 'Напитки',
'https://lenta.com/catalog/sladosti-1028/': 'Сладости',
'https://lenta.com/catalog/konservaciya-94/': 'Консервация',
'https://lenta.com/catalog/sneki-20195/': 'Снеки',
'https://lenta.com/catalog/detskoe-pitanie-19327/': 'Детское питание'
}

DIXY_GOODS_CATEGORIES_DICT = {
'https://dixy.ru/catalog/skidki-po-karte/': 'Скидки по карте', 
'https://dixy.ru/catalog/ovoshchi-frukty/': 'Овощи, фрукты', 
'https://dixy.ru/catalog/gotovaya-eda/': 'Готовая еда', 
'https://dixy.ru/catalog/molochnye-produkty-yaytsa/': 'Молочные продукты, яйцо', 
'https://dixy.ru/catalog/syry/': 'Сыры', 
'https://dixy.ru/catalog/myaso-ptitsa/': 'Мясо, птица', 
'https://dixy.ru/catalog/myasnaya-gastronomiya/': 'Мясная гастрономия', 
'https://dixy.ru/catalog/khleb-i-vypechka/': 'Хлеб и выпечка', 
'https://dixy.ru/catalog/ryba-moreprodukty-ikra/': 'Рыба, морепродукты, икра', 
'https://dixy.ru/catalog/bakaleya/': 'Бакалея', 
'https://dixy.ru/catalog/konservy/': 'Консервы', 
'https://dixy.ru/catalog/zamorojennye-produkty/': 'Замороженные продукты', 
'https://dixy.ru/catalog/sousy-spetsii/': 'Соусы, специи', 
'https://dixy.ru/catalog/konditerskie-izdeliya-torty/': 'Кондитерские изделия, торты', 
'https://dixy.ru/catalog/chipsy-orekhi-i-sneki/': 'Чипсы, орехи и снеки', 
'https://dixy.ru/catalog/chay-kofe-kakao/': 'Чай, кофе, какао', 
'https://dixy.ru/catalog/voda-soki-napitki/': 'Вода, соки, напитки', 
'https://dixy.ru/catalog/dlya-zdorovogo-pitaniya/': 'Для здорового питания', 
'https://dixy.ru/catalog/detskoe-pitanie/': 'Детское питание', 
'https://dixy.ru/catalog/tovary-dlya-detey/': 'Товары для детей', 
'https://dixy.ru/catalog/tovary-dlya-jivotnykh/': 'Товары для животных',
'https://dixy.ru/catalog/bytovaya-khimiya/': 'Бытовая химия', 
'https://dixy.ru/catalog/gigiena-i-kosmetika/': 'Гигиена и косметика', 
'https://dixy.ru/catalog/tovary-dlya-doma-i-dachi/': 'Товары для дома и дачи', 
'https://dixy.ru/catalog/alkogolnye-napitki/': 'Алкогольные напитки'
}

DIXY_FOOD_CATEGORIES_DICT = {
'https://dixy.ru/catalog/ovoshchi-frukty/': 'Овощи, фрукты', 
'https://dixy.ru/catalog/molochnye-produkty-yaytsa/': 'Молочные продукты, яйцо', 
'https://dixy.ru/catalog/syry/': 'Сыры', 
'https://dixy.ru/catalog/myaso-ptitsa/': 'Мясо, птица', 
'https://dixy.ru/catalog/myasnaya-gastronomiya/': 'Мясная гастрономия', 
'https://dixy.ru/catalog/khleb-i-vypechka/': 'Хлеб и выпечка', 
'https://dixy.ru/catalog/ryba-moreprodukty-ikra/': 'Рыба, морепродукты, икра', 
'https://dixy.ru/catalog/bakaleya/': 'Бакалея', 
'https://dixy.ru/catalog/konservy/': 'Консервы', 
'https://dixy.ru/catalog/zamorojennye-produkty/': 'Замороженные продукты', 
'https://dixy.ru/catalog/sousy-spetsii/': 'Соусы, специи', 
'https://dixy.ru/catalog/konditerskie-izdeliya-torty/': 'Кондитерские изделия, торты', 
'https://dixy.ru/catalog/chipsy-orekhi-i-sneki/': 'Чипсы, орехи и снеки', 
'https://dixy.ru/catalog/chay-kofe-kakao/': 'Чай, кофе, какао', 
'https://dixy.ru/catalog/voda-soki-napitki/': 'Вода, соки, напитки', 
'https://dixy.ru/catalog/detskoe-pitanie/': 'Детское питание', 
}


CHIZHIK_CATEGORIES_DICT = {
"https://chizhik.club/catalog/molochnye-produkty-yaytso--264C39140/": "Молочные продукты, яйцо",
"https://chizhik.club/catalog/syry-i-maslo--264C39153/": "Сыры и масло", 
"https://chizhik.club/catalog/krupy-i-makarony--264C39160/": "Крупы и макароны", 
"https://chizhik.club/catalog/khleb-i-vypechka--264C39166/": "Хлеб и выпечка", 
"https://chizhik.club/catalog/maslo-sousy-spetsii--264C39172/": ">Масло, соусы, специи",
"https://chizhik.club/catalog/konservatsiya--264C39207/": "Консервация",
"https://chizhik.club/catalog/myaso-i-ptitsa--264C39184/":"Мясо и птица",
"https://chizhik.club/catalog/myasnaya-gastronomiya--264C39179/": "Мясная гастрономия",
"https://chizhik.club/catalog/ryba-i-moreprodukty--264C39189/" : "Рыба и морепродукты",
"https://chizhik.club/catalog/zamorozhennye-produkty--264C39201/" : "Замороженные продукты",
"https://chizhik.club/catalog/ovoshchi-i-frukty--264C39196/" : "Овощи и фрукты",
"https://chizhik.club/catalog/orekhi-chipsy-sneki--264C39253/" : "Орехи, чипсы, снеки",
"https://chizhik.club/catalog/sladosti-deserty-morozhenoe--264C39235/": "Сладости, десерты, мороженое",
"https://chizhik.club/catalog/chay-kofe--264C39224/" : "Чай, кофе", 
"https://chizhik.club/catalog/napitki--264C39228/" : "Напитки",
"https://chizhik.club/catalog/detskie-tovary--264C39214/": "Детские товары",
"https://chizhik.club/catalog/tovary-dlya-doma--264C39270/": "Товары для дома",
"https://chizhik.club/catalog/sredstva-gigieny--264C39258/": "Средства гигиены",
"https://chizhik.club/catalog/stirka-i-uborka--264C39277/": "Стирка и уборка",
"https://chizhik.club/catalog/tovary-dlya-zhivotnykh--264C39282/": "Товары для животных",
"https://chizhik.club/catalog/odezhda-obuv-tekstil--264C39286/": "Одежда, обувь, текстиль",
"https://chizhik.club/catalog/energetiki--264C39307/": "Энергетики",
"https://chizhik.club/catalog/alkogol--264C39295/": "Алкоголь",
}

CHIZHIK_FOOD_CATEGORIES_DICT = {
"https://chizhik.club/catalog/molochnye-produkty-yaytso--264C39140/": "Молочные продукты, яйцо",
"https://chizhik.club/catalog/syry-i-maslo--264C39153/": "Сыры и масло", 
"https://chizhik.club/catalog/krupy-i-makarony--264C39160/": "Крупы и макароны", 
"https://chizhik.club/catalog/khleb-i-vypechka--264C39166/": "Хлеб и выпечка", 
"https://chizhik.club/catalog/maslo-sousy-spetsii--264C39172/": "Масло, соусы, специи",
"https://chizhik.club/catalog/konservatsiya--264C39207/": "Консервация",
"https://chizhik.club/catalog/myaso-i-ptitsa--264C39184/":"Мясо и птица",
"https://chizhik.club/catalog/myasnaya-gastronomiya--264C39179/": "Мясная гастрономия",
"https://chizhik.club/catalog/ryba-i-moreprodukty--264C39189/" : "Рыба и морепродукты",
"https://chizhik.club/catalog/zamorozhennye-produkty--264C39201/" : "Замороженные продукты",
"https://chizhik.club/catalog/ovoshchi-i-frukty--264C39196/" : "Овощи и фрукты",
"https://chizhik.club/catalog/orekhi-chipsy-sneki--264C39253/" : "Орехи, чипсы, снеки",
"https://chizhik.club/catalog/sladosti-deserty-morozhenoe--264C39235/": "Сладости, десерты, мороженое",
"https://chizhik.club/catalog/chay-kofe--264C39224/" : "Чай, кофе", 
"https://chizhik.club/catalog/napitki--264C39228/" : "Напитки",
"https://chizhik.club/catalog/energetiki--264C39307/": "Энергетики",
}

OKEY_FOOD_CATEGORIES_DICT = {
"https://www.okeydostavka.ru/msk/ovoshchi-i-frukty/ovoshchi" : "Овощи",
"https://www.okeydostavka.ru/msk/ovoshchi-i-frukty/frukty-i-iagody-20" : "Фрукты и ягоды",
"https://www.okeydostavka.ru/msk/ovoshchi-i-frukty/zelen-i-salaty" : "Зелень и салаты",
"https://www.okeydostavka.ru/msk/ovoshchi-i-frukty/orekhi-sukhofrukty" : "Орехи, сухофрукты",
"https://www.okeydostavka.ru/msk/ovoshchi-i-frukty/ovoshchnye-smesi-ovoshchi-kvashennye" : "Овощные смеси, овощи квашенные",
"https://www.okeydostavka.ru/msk/miaso-ptitsa-kolbasy/miaso-20": "Мясо",
"https://www.okeydostavka.ru/msk/miaso-ptitsa-kolbasy/ptitsa-20" : "Птица",
"https://www.okeydostavka.ru/msk/miaso-ptitsa-kolbasy/polufabrikaty-iz-miasa-i-ptitsy" : "Полуфабрикаты из мяса и птицы",
"https://www.okeydostavka.ru/msk/miaso-ptitsa-kolbasy/subprodukty-iz-miasa-i-ptitsy" : "Субпродукты из мяса и птицы",
"https://www.okeydostavka.ru/msk/miaso-ptitsa-kolbasy/kolbasy-varenye" : "Колбасы вареные",
"https://www.okeydostavka.ru/msk/miaso-ptitsa-kolbasy/sosiski-sardel-ki" : "Сосиски, сардельки",
"https://www.okeydostavka.ru/msk/miaso-ptitsa-kolbasy/kolbasy-kopchenye" : "Колбасы копченые",
"https://www.okeydostavka.ru/msk/miaso-ptitsa-kolbasy/miasnye-delikatesy" : "Мясные деликатесы",
"https://www.okeydostavka.ru/msk/miaso-ptitsa-kolbasy/pashtety-liver" : "Паштеты, ливер",
"https://www.okeydostavka.ru/msk/miaso-ptitsa-kolbasy/steiki" : "Стейки",
"https://www.okeydostavka.ru/msk/ryba-moreprodukty-i-ikra/ryba-okhlazhdennaia-i-zamorozhennaia" : "Рыба охлажденная и замороженная",
"https://www.okeydostavka.ru/msk/ryba-moreprodukty-i-ikra/rybnaia-gastronomiia/preservy" : "Пресервы",
"https://www.okeydostavka.ru/msk/ryba-moreprodukty-i-ikra/rybnaia-gastronomiia/krabovoe-miaso-i-palochki" : "Крабовое мясо и палочки",
"https://www.okeydostavka.ru/msk/ryba-moreprodukty-i-ikra/rybnaia-gastronomiia/ryba-solenaia-i-kopchenaia" : "Рыба соленая и копченая",
"https://www.okeydostavka.ru/msk/ryba-moreprodukty-i-ikra/rybnaia-gastronomiia/ryba-vialenaia-sushenaia-sneki-rybnye" : "Рыба вяленая, сушеная, снэки рыбные",
"https://www.okeydostavka.ru/msk/ryba-moreprodukty-i-ikra/moreprodukty" : "Морепродукты",
"https://www.okeydostavka.ru/msk/ryba-moreprodukty-i-ikra/ikra" : "Икра",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/molochnye-produkty/maslenitsa-s-prostokvashino-20-3074457345616886229" : "Масленица с Простоквашино",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/molochnye-produkty/moloko-i-slivki" : "Молоко и сливки",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/molochnye-produkty/iogurty-i-tvorozhki" : "Йогурты и творожки",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/molochnye-produkty/tvorozhnye-izdeliia" : "Творожные изделия",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/molochnye-produkty/produkty-molochnye-dlia-detei-i-kormiashchikh-mam" : "Продукты молочные для детей и кормящих мам",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/molochnye-produkty/kislomolochnye-produkty" : "Кисломолочные продукты",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/molochnye-produkty/maslo-slivochnoe-i-margarin" : "Масло сливочное и маргарин",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/molochnye-produkty/smetana" : "Сметана",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/molochnye-produkty/deserty-kashi-molochnye" : "Десерты, каши молочные",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/molochnye-produkty/rastitel-nye-produkty" : "Растительные продукты",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/molochnye-produkty/maslo-slivochnoe-i-margarin" : "Масло сливочное и маргарин",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/sgushchennoe-moloko" : "Сгущенное молоко",
"https://www.okeydostavka.ru/msk/molochnye-produkty-iaitso/iaitso" : "Яйцо",
"https://www.okeydostavka.ru/msk/syry/tverdye-i-polutverdye-syry" :"Твердые и полутвердые сыры",
"https://www.okeydostavka.ru/msk/syry/plavlenye-syry" : "Плавленые сыры",
"https://www.okeydostavka.ru/msk/syry/delikatesnye-i-desertnye-syry" : "Деликатесные и десертные сыры",
"https://www.okeydostavka.ru/msk/syry/tvorozhnye-syry" : "Творожные сыры",
"https://www.okeydostavka.ru/msk/syry/rassol-nye-syry" : "Рассольные сыры",
"https://www.okeydostavka.ru/msk/syry/kopchenye-syry" : "Копченые сыры",
"https://www.okeydostavka.ru/msk/zamorozka-i-gotovaia-eda/pitstsa-i-testo" : "Пицца и тесто",
"https://www.okeydostavka.ru/msk/zamorozka-i-gotovaia-eda/pel-meni-i-muchnye-izdeliia" : "Пельмени и мучные изделия",
"https://www.okeydostavka.ru/msk/zamorozka-i-gotovaia-eda/gotovye-bliuda" : "Готовые блюда",
"https://www.okeydostavka.ru/msk/zamorozka-i-gotovaia-eda/morozhenoe" : "Мороженое",
"https://www.okeydostavka.ru/msk/zamorozka-i-gotovaia-eda/ovoshchi-i-iagody-zamorozhennye" : "Овощи и ягоды замороженные",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/sportivnoe-pitanie-i-vitaminy" : "Спортивное питание и витамины",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/produkty-dlia-pokhudeniia" : "Продукты для похудения",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/vse-dlia-vypechki-desertov-20" : "Все для выпечки, десертов",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/krupy-i-bobovye" : "Крупы и бобовые",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/makaronnye-izdeliia" : "Макаронные изделия",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/rybnye-konservy" : "Рыбные консервы",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/miasnye-konservy" : "Мясные консервы",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/ovoshchi-i-griby-konservirovannye" : "Овощи и грибы консервированные",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/frukty-i-iagody-konservirovannye" : "Фрукты и ягоды консервированные",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/med" : "Мёд",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/gotovye-bliuda-konservirovannye" : "Готовые блюда консервированные",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/sakhar-i-sol-" : "Сахар и соль",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/muka-smesi-dlia-vypechki-20" : "Мука, смеси для выпечки",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/sukhie-zavtraki" : "Сухие завтраки",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/supy-i-bliuda-bystrogo-prigotovleniia" : "Супы и блюда быстрого приготовления",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/chipsy-sukhariki-sneki" : "Чипсы, сухарики, снэки",
"https://www.okeydostavka.ru/msk/bakaleia-i-konservy/dieticheskie-produkty" : "Диетические продукты",
"https://www.okeydostavka.ru/msk/rastitel-nye-masla-sousy-i-pripravy/maslo-rastitel-noe" : "Масло растительное",
"https://www.okeydostavka.ru/msk/rastitel-nye-masla-sousy-i-pripravy/spetsii-pripravy" : "Специи, приправы",
"https://www.okeydostavka.ru/msk/rastitel-nye-masla-sousy-i-pripravy/tomatnye-pasty-ketchupy" : "Томатные пасты, кетчупы",
"https://www.okeydostavka.ru/msk/rastitel-nye-masla-sousy-i-pripravy/maionez" : "Майонез",
"https://www.okeydostavka.ru/msk/rastitel-nye-masla-sousy-i-pripravy/sousy-zapravki" : "Соусы, заправки",
"https://www.okeydostavka.ru/msk/rastitel-nye-masla-sousy-i-pripravy/uksus-limonnyi-sok" : "Уксус, лимонный сок",
"https://www.okeydostavka.ru/msk/rastitel-nye-masla-sousy-i-pripravy/aziatskaia-kukhnia" : "Азиатская кухня",
"https://www.okeydostavka.ru/msk/sladosti-khleb/khlebobulochnye-izdeliia/khleb-baton-lepeshki-lavash" : "Хлеб, батон, лепешки, лаваш",
"https://www.okeydostavka.ru/msk/sladosti-khleb/khlebobulochnye-izdeliia/vypechka-izdeliia-sdobnye" : "Выпечка, изделия сдобные",
"https://www.okeydostavka.ru/msk/sladosti-khleb/khlebobulochnye-izdeliia/khlebtsy-sukhari-baranki-sushki" : "Хлебцы, сухари, баранки, сушки",
"https://www.okeydostavka.ru/msk/sladosti-khleb/shokoladnaia-plitka" : "Шоколадная плитка",
"https://www.okeydostavka.ru/msk/sladosti-khleb/shokoladnye-batonchiki-pasta-iaitsa-drazhe" : "Шоколадные батончики, паста, яйца, драже",
"https://www.okeydostavka.ru/msk/sladosti-khleb/konfety" : "Конфеты",
"https://www.okeydostavka.ru/msk/sladosti-khleb/muchnye-konditerskie-izdeliia" : "Мучные кондитерские изделия",
"https://www.okeydostavka.ru/msk/sladosti-khleb/marmelad-sufle-zefir-pastila" : "Мармелад, суфле, зефир, пастила",
"https://www.okeydostavka.ru/msk/sladosti-khleb/torty-i-pirozhnye" : "Торты и пирожные",
"https://www.okeydostavka.ru/msk/sladosti-khleb/zhevatel-nye-rezinki-osvezhaiushchie-konfety" : "Жевательные резинки, освежающие конфеты",
"https://www.okeydostavka.ru/msk/sladosti-khleb/vostochnye-sladosti" : "Восточные сладости",
"https://www.okeydostavka.ru/msk/goriachie-i-kholodnye-napitki/energeticheskie-napitki" : "Энергетические напитки",
"https://www.okeydostavka.ru/msk/goriachie-i-kholodnye-napitki/napitki-sokosoderzhashchie" : "Напитки сокосодержащие",
"https://www.okeydostavka.ru/msk/goriachie-i-kholodnye-napitki/bezalkogol-nye-vina" : "Безалкогольные вина",
"https://www.okeydostavka.ru/msk/goriachie-i-kholodnye-napitki/voda" : "Вода",
"https://www.okeydostavka.ru/msk/goriachie-i-kholodnye-napitki/chai" : "Чай",
"https://www.okeydostavka.ru/msk/goriachie-i-kholodnye-napitki/kofe-kakao-tsikorii/kofe" : "Кофе",
"https://www.okeydostavka.ru/msk/goriachie-i-kholodnye-napitki/kofe-kakao-tsikorii/kakao-shokoladnye-i-kofeinye-napitki" : "Какао, шоколадные и кофейные напитки",
"https://www.okeydostavka.ru/msk/goriachie-i-kholodnye-napitki/kofe-kakao-tsikorii/tsikorii" : "Цикорий",
"https://www.okeydostavka.ru/msk/goriachie-i-kholodnye-napitki/soki-nektary-morsy" : "Соки, нектары, морсы",
"https://www.okeydostavka.ru/msk/goriachie-i-kholodnye-napitki/limonady-20" : "Лимонады",
"https://www.okeydostavka.ru/msk/goriachie-i-kholodnye-napitki/kholodnyi-chai" : "Холодный чай",
"https://www.okeydostavka.ru/msk/goriachie-i-kholodnye-napitki/kvas" : "Квас",
"https://www.okeydostavka.ru/msk/detskie-tovary-i-igrushki/detskoe-pitanie/piure-detskoe" : "Пюре детское",
"https://www.okeydostavka.ru/msk/detskie-tovary-i-igrushki/detskoe-pitanie/napitki-dlia-detskogo-pitaniia" : "Напитки для детского питания",
"https://www.okeydostavka.ru/msk/detskie-tovary-i-igrushki/detskoe-pitanie/kashi-detskie" : "Каши детские",
"https://www.okeydostavka.ru/msk/detskie-tovary-i-igrushki/detskoe-pitanie/molochnye-smesi-sukhie" : "Молочные смеси сухие",
"https://www.okeydostavka.ru/msk/detskie-tovary-i-igrushki/detskoe-pitanie/poleznyi-perekus" : "Полезный перекус"
}


PEREKRESTOK_FOOD_CATEGORIES_DICT = {
"https://www.perekrestok.ru/cat/c/114/moloko" : "Молоко",
"https://www.perekrestok.ru/cat/c/122/syr" : "Сыр",
"https://www.perekrestok.ru/cat/c/117/tvorog" : "Творог",
"https://www.perekrestok.ru/cat/c/656/syrki" : "Сырки",
"https://www.perekrestok.ru/cat/c/119/jogurty" : "Йогурты",
"https://www.perekrestok.ru/cat/c/657/tvorozki" : "Творожки",
"https://www.perekrestok.ru/cat/c/658/deserty-i-sneki" : "Десерты и снеки",
"https://www.perekrestok.ru/cat/c/123/ajca" : "Яйца",
"https://www.perekrestok.ru/cat/c/121/maslo" : "Масло",
"https://www.perekrestok.ru/cat/c/659/margarin" : "Маргарин",
"https://www.perekrestok.ru/cat/c/660/spred" : "Спред",
"https://www.perekrestok.ru/cat/c/120/kislomolocnye-produkty" : "Кисломолочные продукты",
"https://www.perekrestok.ru/cat/c/118/smetana" : "Сметана",
"https://www.perekrestok.ru/cat/c/115/slivki" : "Сливки",
"https://www.perekrestok.ru/cat/c/124/molocnye-konservy" : "Молочные консервы",
"https://www.perekrestok.ru/cat/c/116/molocnye-koktejli" : "Молочные коктейли",
"https://www.perekrestok.ru/cat/c/150/ovosi" : "Овощи",
"https://www.perekrestok.ru/cat/c/153/frukty" : "Фрукты",
"https://www.perekrestok.ru/cat/c/154/agody" : "Ягоды",
"https://www.perekrestok.ru/cat/c/151/zelen-i-salaty" : "Зелень и салаты",
"https://www.perekrestok.ru/cat/c/155/griby" : "Грибы",
"https://www.perekrestok.ru/cat/c/149/solena" : "Соленья",
"https://www.perekrestok.ru/cat/c/105/makarony" : "Макароны",
"https://www.perekrestok.ru/cat/c/104/rastitelnoe-maslo" : "Растительное масло",
"https://www.perekrestok.ru/cat/c/107/krupy" : "Крупы",
"https://www.perekrestok.ru/cat/c/745/bobovye" : "Бобовые",
"https://www.perekrestok.ru/cat/c/103/specii-pripravy-i-pranosti" : "Специи, приправы и пряности",
"https://www.perekrestok.ru/cat/c/106/muka" : "Мука",
"https://www.perekrestok.ru/cat/c/102/komponenty-dla-vypecki" : "Компоненты для выпечки",
"https://www.perekrestok.ru/cat/c/101/sol" : "Соль",
"https://www.perekrestok.ru/cat/c/202/cipsy" : "Чипсы",
"https://www.perekrestok.ru/cat/c/774/nacos" : "Начос",
"https://www.perekrestok.ru/cat/c/709/sneki" : "Снеки",
"https://www.perekrestok.ru/cat/c/710/popkorn" : "Попкорн",
"https://www.perekrestok.ru/cat/c/711/suhariki" : "Сухарики",
"https://www.perekrestok.ru/cat/c/712/grenki" : "Гренки",
"https://www.perekrestok.ru/cat/c/713/kukuruznye-palocki" : "Кукурузные палочки",
"https://www.perekrestok.ru/cat/c/199/suski-i-baranki" : "Сушки и баранки",
"https://www.perekrestok.ru/cat/c/714/solomki" : "Соломки",
"https://www.perekrestok.ru/cat/c/715/hlebnye-palocki" : "Хлебные палочки",
"https://www.perekrestok.ru/cat/c/716/suhary" : "Сухари",
"https://www.perekrestok.ru/cat/c/717/hlebcy" : "Хлебцы",
"https://www.perekrestok.ru/cat/c/718/vodorosli" : "Водоросли",
"https://www.perekrestok.ru/cat/c/197/pecene" :"Печенье",
"https://www.perekrestok.ru/cat/c/702/vafli" : "Вафли",
# "https://www.perekrestok.ru//cat/c/703/praniki" : "Пряники",
"https://www.perekrestok.ru/cat/c/195/sokolad" : "Шоколад", 
"https://www.perekrestok.ru/cat/c/203/batonciki" : "Батончики",
"https://www.perekrestok.ru/cat/c/204/sokoladnye-i-orehovye-pasty" : "Шоколадные и ореховые пасты",
"https://www.perekrestok.ru/cat/c/193/konfety" : "Конфеты",
"https://www.perekrestok.ru/cat/c/201/torty" : "Торты",
"https://www.perekrestok.ru/cat/c/704/piroznye" : "Пирожные",
"https://www.perekrestok.ru/cat/c/198/pirogi-sdoba-keksy-rulety" : "Пироги, сдоба, кексы, рулеты",
"https://www.perekrestok.ru/cat/c/705/zefir" : "Зефир",
"https://www.perekrestok.ru/cat/c/191/marmelad" : "Мармелад",
"https://www.perekrestok.ru/cat/c/706/pastila" : "Пастила",
"https://www.perekrestok.ru/cat/c/189/diabeticeskie-sladosti" : "Диабетические сладости",
"https://www.perekrestok.ru/cat/c/194/ledency" : "Леденцы",
"https://www.perekrestok.ru/cat/c/707/draze" : "Драже",
"https://www.perekrestok.ru/cat/c/188/vostocnye-sladosti-halva" : "Восточные сладости, халва",
"https://www.perekrestok.ru/cat/c/190/zevatelnaa-rezinka" : "Жевательная резинка",
"https://www.perekrestok.ru/cat/c/321/morozenoe" : "Мороженое",
"https://www.perekrestok.ru/cat/c/208/voda" : "Вода",
"https://www.perekrestok.ru/cat/c/209/gazirovannye-napitki" : "Газированные напитки", 
"https://www.perekrestok.ru/cat/c/211/soki" : "Соки",
"https://www.perekrestok.ru/cat/c/737/nektary" : "Нектары",
"https://www.perekrestok.ru/cat/c/212/kvas" : "Квас",
"https://www.perekrestok.ru/cat/c/215/rastitelnye-napitki" : "Растительные напитки",
"https://www.perekrestok.ru/cat/c/210/holodnyj-caj" : "Холодный чай",
"https://www.perekrestok.ru/cat/c/207/bezalkogolnoe-pivo" : "Безалкогольное пиво",
"https://www.perekrestok.ru/cat/c/739/bezalkogolnoe-vino" : "Безалкогольное вино",
"https://www.perekrestok.ru/cat/c/740/sokosoderzasie-napitki" : "Сокосодержащие напитки",
"https://www.perekrestok.ru/cat/c/213/smuzi" : "Смузи",
"https://www.perekrestok.ru/cat/c/206/energeticeskie-napitki" : "Энергетические напитки",
"https://www.perekrestok.ru/cat/c/214/morsy" : "Морсы",
"https://www.perekrestok.ru/cat/c/742/kiseli" : "Кисели",
"https://www.perekrestok.ru/cat/c/743/kompoty" : "Компоты",
"https://www.perekrestok.ru/cat/c/744/sbiten-i-uzvary" : "Сбитень и узвары",
"https://www.perekrestok.ru/cat/c/216/diabeticeskie-napitki" : "Диабетические напитки",
"https://www.perekrestok.ru/cat/c/196/nasa-pekarna" : "Наша пекарня",
"https://www.perekrestok.ru/cat/c/243/hleb" : "Хлеб",
"https://www.perekrestok.ru/cat/c/1152/picca" : "Пицца",
"https://www.perekrestok.ru/cat/c/244/lavas-i-lepeski" : "Лаваш и лепёшки",
"https://www.perekrestok.ru/cat/c/245/hlebcy" : "Хлебцы",
"https://www.perekrestok.ru/cat/c/246/hlebobulocnye-izdelia" : "Хлебобулочные изделия",
"https://www.perekrestok.ru/cat/c/1320/vse-maso" : "Всё мясо",
"https://www.perekrestok.ru/cat/c/138/maso-pticy" : "Мясо птицы",
"https://www.perekrestok.ru/cat/c/951/saslyk" : "Шашлык",
"https://www.perekrestok.ru/cat/c/142/govadina" : "Говядина",
"https://www.perekrestok.ru/cat/c/137/baranina" : "Баранина",
"https://www.perekrestok.ru/cat/c/143/krolik" : "Кролик",
"https://www.perekrestok.ru/cat/c/135/polufabrikaty" : "Полуфабрикаты",
"https://www.perekrestok.ru/cat/c/139/svinina" : "Свинина",
"https://www.perekrestok.ru/cat/c/136/delikatesy-i-kopcenosti" : "Деликатесы и копчёности",
"https://www.perekrestok.ru/cat/c/145/fars" : "Фарш",
"https://www.perekrestok.ru/cat/c/141/subprodukty" : "Субпродукты",
"https://www.perekrestok.ru/cat/c/144/holodcy" : "Холодцы",
"https://www.perekrestok.ru/cat/c/778/pastety" : "Паштеты",
"https://www.perekrestok.ru/cat/c/781/zalivnoe" : "Заливное",
"https://www.perekrestok.ru/cat/c/779/studni" : "Студни",
"https://www.perekrestok.ru/cat/c/133/kolbasa" : "Колбаса",
"https://www.perekrestok.ru/cat/c/783/vetcina" : "Ветчина",
"https://www.perekrestok.ru/cat/c/134/sosiski" : "Сосиски",
"https://www.perekrestok.ru/cat/c/784/sardelki" : "Сардельки",
"https://www.perekrestok.ru/cat/c/785/spikacki" : "Шпикачки",
"https://www.perekrestok.ru/cat/c/809/delikatesy-i-kopcenosti" : "Деликатесы и копчёности",
"https://www.perekrestok.ru/cat/c/807/holodcy" : "Холодцы",
"https://www.perekrestok.ru/cat/c/808/pastety" : "Паштеты",
"https://www.perekrestok.ru/cat/c/810/zalivnoe" : "Заливное",
"https://www.perekrestok.ru/cat/c/811/studni" : "Студни",
"https://www.perekrestok.ru/cat/c/812/vsa-ryba" : "Вся рыба",
"https://www.perekrestok.ru/cat/c/175/solenaa-marinovannaa-ryba" : "Солёная, маринованная рыба",
"https://www.perekrestok.ru/cat/c/176/ohlazdennaa-ryba" : "Охлаждённая рыба",
"https://www.perekrestok.ru/cat/c/273/zamorozennaa-ryba" : "Замороженная рыба",
"https://www.perekrestok.ru/cat/c/177/kopcenaa-ryba" : "Копчёная рыба",
"https://www.perekrestok.ru/cat/c/181/rybnye-konservy-i-kulinaria" : "Рыбные консервы и кулинария",
"https://www.perekrestok.ru/cat/c/794/valenaa-ryba" : "Вяленая рыба",
"https://www.perekrestok.ru/cat/c/178/susenaa-ryba" : "Сушёная рыба",
"https://www.perekrestok.ru/cat/c/184/rybnye-preservy" : "Рыбные пресервы",
"https://www.perekrestok.ru/cat/c/186/sobstvennoe-proizvodstvo" : "Собственное производство",
"https://www.perekrestok.ru/cat/c/58/picca-vareniki-pelmeni-bliny" : "Пицца, вареники, пельмени, блины",
"https://www.perekrestok.ru/cat/c/55/moreprodukty" : "Морепродукты",
"https://www.perekrestok.ru/cat/c/59/ovosi-i-smesi" : "Овощи и смеси",
"https://www.perekrestok.ru/cat/c/56/zamorozennye-polufabrikaty" : "Замороженные полуфабрикаты",
"https://www.perekrestok.ru/cat/c/57/ryba" : "Рыба",
"https://www.perekrestok.ru/cat/c/60/kotlety-naggetsy" : "Котлеты, наггетсы",
"https://www.perekrestok.ru/cat/c/61/agody-i-frukty" : "Ягоды и фрукты",
"https://www.perekrestok.ru/cat/c/63/maso-ptica-i-subprodukty" : "Мясо, птица и субпродукты",
"https://www.perekrestok.ru/cat/c/62/zamorozennye-deserty" : "Замороженные десерты",
"https://www.perekrestok.ru/cat/c/305/led" : "Лёд",
"https://www.perekrestok.ru/cat/c/180/ikra" : "Икра",
"https://www.perekrestok.ru/cat/c/182/krabovoe-maso-i-palocki" : "Крабовое мясо и палочки",
"https://www.perekrestok.ru/cat/c/179/krevetki" : "Креветки",
"https://www.perekrestok.ru/cat/c/787/midii" : "Мидии",
"https://www.perekrestok.ru/cat/c/786/kalmary" : "Кальмары",
"https://www.perekrestok.ru/cat/c/788/koktejli-iz-moreproduktov" : "Коктейли из морепродуктов",
"https://www.perekrestok.ru/cat/c/789/ustricy" : "Устрицы",
"https://www.perekrestok.ru/cat/c/792/preservy-iz-moreproduktov" : "Пресервы из морепродуктов",
"https://www.perekrestok.ru/cat/c/276/voda-i-napitki" : "Вода и напитки",
"https://www.perekrestok.ru/cat/c/230/detskoe-pitanie" : "Детское питание",
"https://www.perekrestok.ru/cat/c/277/detskie-smesi-i-zameniteli" : "Детские смеси и заменители",
"https://www.perekrestok.ru/cat/c/218/sousy" : "Соусы",
"https://www.perekrestok.ru/cat/c/221/majonez" : "Майонез",
"https://www.perekrestok.ru/cat/c/219/ketcupy-i-tomatnye-sousy" : "Кетчупы и томатные соусы",
"https://www.perekrestok.ru/cat/c/220/tomatnaa-pasta" : "Томатная паста",
"https://www.perekrestok.ru/cat/c/223/gorcica" : "Горчица",
"https://www.perekrestok.ru/cat/c/746/hren" : "Хрен",
"https://www.perekrestok.ru/cat/c/222/uksus" : "Уксус",
"https://www.perekrestok.ru/cat/c/80/kofe" : "Кофе",
"https://www.perekrestok.ru/cat/c/82/caj" : "Чай",
"https://www.perekrestok.ru/cat/c/83/sahar" : "Сахар",
"https://www.perekrestok.ru/cat/c/81/kakao" : "Какао",
"https://www.perekrestok.ru/cat/c/766/goracij-sokolad" : "Горячий шоколад",
"https://www.perekrestok.ru/cat/c/225/hlopa" : "Хлопья",
"https://www.perekrestok.ru/cat/c/747/musli" : "Мюсли",
"https://www.perekrestok.ru/cat/c/748/podusecki" : "Подушечки",
"https://www.perekrestok.ru/cat/c/749/sariki" : "Шарики",
"https://www.perekrestok.ru/cat/c/750/kolecki" : "Колечки",
"https://www.perekrestok.ru/cat/c/751/figurki" : "Фигурки",
"https://www.perekrestok.ru/cat/c/752/granola" : "Гранола",
"https://www.perekrestok.ru/cat/c/754/ris" : "Рис",
"https://www.perekrestok.ru/cat/c/172/kasi" : "Каши",
"https://www.perekrestok.ru/cat/c/755/kasi-bystrogo-prigotovlenia" : "Каши быстрого приготовления",
"https://www.perekrestok.ru/cat/c/170/lapsa" : "Лапша",
"https://www.perekrestok.ru/cat/c/169/supy" : "Супы",
"https://www.perekrestok.ru/cat/c/171/pure" : "Пюре",
"https://www.perekrestok.ru/cat/c/756/kasi" : "Каши",
"https://www.perekrestok.ru/cat/c/173/vtorye-bluda" : "Вторые блюда",
"https://www.perekrestok.ru/cat/c/76/ovosnye-konservy" : "Овощные консервы",
"https://www.perekrestok.ru/cat/c/75/rybnye-konservy" : "Рыбные консервы",
"https://www.perekrestok.ru/cat/c/78/masnye-konservy" : "Мясные консервы",
"https://www.perekrestok.ru/cat/c/77/fruktovye-konservy" : "Фруктовые консервы",
"https://www.perekrestok.ru/cat/c/24/diabeticeskaa-produkcia" : "Диабетическая продукция",
"https://www.perekrestok.ru/cat/c/65/sportivnoe-pitanie-i-bad" : "Спортивное питание и БАД",
"https://www.perekrestok.ru/cat/c/251/bez-glutena" : "Без глютена",
"https://www.perekrestok.ru/cat/c/252/superfud" : "Суперфуд",
"https://www.perekrestok.ru/cat/c/253/poleznyj-perekus" : "Полезный перекус",
"https://www.perekrestok.ru/cat/c/254/rastitelnye-napitki" : "Растительные напитки",
"https://www.perekrestok.ru/cat/c/255/pravilnye-sladosti" : "Правильные сладости",
"https://www.perekrestok.ru/cat/c/257/napitki-s-polzoj" : "Напитки с пользой",
"https://www.perekrestok.ru/cat/c/1676/funkcionalnye-produkty" : "Функциональные продукты",
"https://www.perekrestok.ru/cat/c/159/orehi" : "Орехи",
"https://www.perekrestok.ru/cat/c/161/semecki" : "Семечки",
"https://www.perekrestok.ru/cat/c/158/smesi-orehov-i-suhofruktov" : "Смеси орехов и сухофруктов",
"https://www.perekrestok.ru/cat/c/160/suhofrukty" : "Сухофрукты",
"https://www.perekrestok.ru/cat/c/112/med" : "Мёд",
"https://www.perekrestok.ru/cat/c/111/varene" : "Варенье",
"https://www.perekrestok.ru/cat/c/109/dzem" : "Джем",
"https://www.perekrestok.ru/cat/c/775/konfitur" : "Конфитюр",
"https://www.perekrestok.ru/cat/c/110/siropy" : "Сиропы",
}
